---
deployment:
  tasks:
    - export DEPLOYPATH=/home/graceklr/public_html/
    - /bin/rm -R $DEPLOYPATH/*
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp gabout.html $DEPLOYPATH
    - /bin/cp gconnect.html $DEPLOYPATH
    # - /bin/cp -R images $DEPLOYPATH
